import test from 'node:test';import assert from 'node:assert/strict';import {registerHooks} from 'node:module';import {readFileSync} from 'node:fs';
registerHooks({resolve(s,c,n){return n(s.startsWith('.')&&!c.parentURL?.includes('/node_modules/')&&!/\.[a-z]+$/i.test(s)?`${s}.ts`:s,c);}});
const {stickDirection,stickThumb}=await import('../src/controls.ts');
const {installWorldMap,loadWorldMap}=await import('../../../../Games/games/boxbound/world-map.ts');
installWorldMap(await loadWorldMap(new URL('../../../../Games/games/boxbound/levels/index.json',import.meta.url),async u=>JSON.parse(readFileSync(u,'utf8'))));
const {MobileSession}=await import('../src/session.ts');const {createGame}=await import('../../../../Games/games/boxbound/levels.ts');const {validState,clone}=await import('../../../../Games/games/boxbound/model.ts');
function session(){const s=new MobileSession();s.scene={moving:false,transitioning:false,celebrating:false,airborne:false,home:true,show(){},cancelMotion(){this.airborne=false;},jumpInPlace(){this.airborne=true;}};s.load(createGame());return s;}
test('joystick dead zone, cardinal snapping and hysteresis avoid diagonal jitter',()=>{assert.equal(stickDirection(5,8),null);assert.deepEqual(stickDirection(-50,10),[-1,0,0]);assert.deepEqual(stickDirection(4,-50),[0,0,-1]);assert.deepEqual(stickDirection(30,32,[1,0,0]),[1,0,0]);assert.deepEqual(stickDirection(35,30,[0,0,1]),[0,0,1]);assert(Math.hypot(...Object.values(stickThumb(200,150)))<=43.00001);});
test('held stick repeats moves and release cancels future movement',()=>{const s=session();s.setDirection([0,0,-1]);s.tick(200);s.tick(400);assert.equal(s.state.moves,2);s.setDirection(null);s.tick(600);assert.equal(s.state.moves,2);assert(validState(s.state));});
test('jump combines with direction; canceled input cannot survive suspension',()=>{const s=session();s.setDirection([1,0,0]);s.jump();assert(s.scene.airborne);assert(s.state.moves>0);s.cancel();s.paused=true;const before=clone(s.state);s.tick(1000);assert.deepEqual(s.state,before);assert.equal(s.held,null);});
test('undo waits for landing and then restores full state',()=>{const s=session(),before=clone(s.state);s.act({type:'move',dir:[0,0,-1]});s.scene.moving=true;s.undo();assert.notDeepEqual(s.state.player,before.player);s.tick(400);assert.equal(s.history.length,1);s.scene.moving=false;s.tick(600);assert.deepEqual(s.state.player,before.player);assert.equal(s.state.moves,0);});
test('exiting a level preserves progress and moved puzzle objects',()=>{const s=session(),g=s.state.boxes.find(b=>b.id==='pp-gateway-1');s.state.player={room:g.inside,pos:[...s.state.rooms[g.inside].spawn],facing:[0,0,-1],route:[{box:'pp-museum',from:'world',entry:[8,0,3]},{box:'pp-chapter-intro',from:'pp-hub',entry:[3,0,6]},{box:g.id,from:g.room,entry:[g.pos[0],0,g.pos[2]+1]}]};s.state.completed=[1];const boxes=clone(s.state.boxes);s.exit();assert.equal(s.state.player.room,g.room);assert.deepEqual(s.state.boxes,boxes);assert.deepEqual(s.state.completed,[1]);assert(validState(s.state));});
test('Android compatibility methods preserve reversal without mutating input',async()=>{
 const reverse=Object.getOwnPropertyDescriptor(Array.prototype,'toReversed'),find=Object.getOwnPropertyDescriptor(Array.prototype,'findLastIndex');
 try{delete Array.prototype.toReversed;delete Array.prototype.findLastIndex;const {installGameRuntime}=await import('../src/runtime.ts');installGameRuntime();const a=[1,2,1];assert.deepEqual(a.toReversed(),[1,2,1]);assert.equal(a.findLastIndex(v=>v===1),2);const b=[1,2,3];assert.deepEqual(b.toReversed(),[3,2,1]);assert.deepEqual(b,[1,2,3]);}
 finally{if(reverse)Object.defineProperty(Array.prototype,'toReversed',reverse);if(find)Object.defineProperty(Array.prototype,'findLastIndex',find);}
});

test('jump with held stick climbs onto a box without pushing it',()=>{const s=session();s.state.player.pos=[7,0,15];const box=clone(s.state.boxes.find(b=>b.id==='island-weight'));s.setDirection([0,0,-1]);s.jump();assert.deepEqual(s.state.player.pos,[7,1,14]);assert.deepEqual(s.state.boxes.find(b=>b.id===box.id),box);assert.equal(s.history.at(-1).jump,true);});
