import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const compiled=ts.transpileModule(readFileSync(new URL('../../../bridge/audio/pcm-bank.ios.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText;
test('native PCM bank preloads once, bounds voices, protects loops, uses no audio thread JS callbacks and handles interruptions',async()=>{
 const nodes=[],notifications=new Map();let reads=0,removed=0,interruptions=0;
 const engine={mainMixerNode:{},running:false,attachNode(){},connectToFormat(){},prepare(){},startAndReturnError(){this.running=true;return true;},pause(){this.running=false;},stop(){this.running=false;},detachNode(){}};
 const globals={AVAudioEngine:{new:()=>engine},AVAudioSession:{sharedInstance:()=>({setCategoryError:()=>true,setActiveError:()=>true})},AVAudioSessionCategoryAmbient:'ambient',NSURL:{fileURLWithPath:p=>p},AVAudioFile:{alloc:()=>({initForReadingError:()=>({length:4410,processingFormat:{channelCount:1,sampleRate:44100},readIntoBufferError(b){reads++;b.frameLength=4410;return true;}})})},AVAudioPCMBuffer:{alloc:()=>({initWithPCMFormatFrameCapacity:format=>({format,frameLength:0})})},AVAudioPlayerNode:{new:()=>{const node={plays:0,stops:0,stop(){this.stops++;},scheduleBufferAtTimeOptionsCompletionHandler(buffer,time,options,callback){assert.equal(time,null);assert.equal(callback,null);this.loop=options;},play(){this.plays++;}};nodes.push(node);return node;}},AVAudioPlayerNodeBufferOptions:{Loops:1},NSNotificationCenter:{defaultCenter:{addObserverForNameObjectQueueUsingBlock(name,object,queue,callback){notifications.set(name,callback);return{};},removeObserver(){removed++;}}},NSOperationQueue:{mainQueue:{}},AVAudioSessionInterruptionNotification:'interruption',AVAudioSessionRouteChangeNotification:'route',AVAudioEngineConfigurationChangeNotification:'config',AVAudioSessionInterruptionTypeKey:'kind',AVAudioSessionInterruptionType:{Began:1},AVAudioSessionRouteChangeReasonKey:'reason',AVAudioSessionRouteChangeReason:{OldDeviceUnavailable:2},NSProcessInfo:{processInfo:{systemUptime:1}}};
 Object.assign(globalThis,globals);
 try{const {NativePcmAudioBank}=await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);const bank=new NativePcmAudioBank(Array.from({length:13},(_,i)=>({id:String(i),path:'fixture',seconds:.1})),()=>interruptions++);assert.equal(bank.snapshot().error,null);assert.equal(reads,13);assert.equal(nodes.length,12);
 const shot=(channel,priority=2,loop=false)=>bank.play('0',{channel,priority,loop,gain:.3,pan:.2});assert.equal(shot('inactive'),false);bank.unlock();assert.equal(shot('laser',100,true),true);for(let i=0;i<11;i++)assert.equal(shot('sfx'+i),true);assert.equal(bank.snapshot().voices,12);assert.equal(shot('weak',0),false);assert.equal(shot('boss',5),true);assert.equal(nodes[0].stops,1);assert.equal(nodes[0].loop,1);assert.equal(nodes.length,12);assert.equal(reads,13);
 NSProcessInfo.processInfo.systemUptime+=1;assert.equal(bank.snapshot().voices,1);assert.equal(shot('again'),true);bank.stop('laser');assert.equal(bank.snapshot().voices,1);notifications.get('interruption')({userInfo:{objectForKey:()=>1}});assert.equal(interruptions,1);assert.equal(bank.snapshot().running,false);assert.equal(bank.snapshot().voices,0);assert.equal(shot('paused'),false);
 bank.unlock();assert.equal(shot('resume'),true);notifications.get('route')({userInfo:{objectForKey:()=>2}});assert.equal(interruptions,2);bank.dispose();bank.dispose();bank.unlock();assert.equal(shot('disposed'),false);assert.equal(removed,3);assert.equal(bank.snapshot().pcmBytes,0);assert.equal(bank.snapshot().nodeCount,0);
 }finally{for(const key of Object.keys(globals))delete globalThis[key];}
});
