import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { patchQueueSource } from '../scripts/patch-canvas.mjs';
test('Canvas texture upload accepts ArrayBuffer and preserves view byte ranges', () => {
  const source = readFileSync(new URL('../node_modules/@nativescript/canvas/WebGPU/GPUQueue.js', import.meta.url), 'utf8');
  const patched = patchQueueSource(source);
  assert.equal(patchQueueSource(patched), patched);
  const native_ = Symbol();
  const GPUQueue = new Function('native_', patched.replace(/^import .*;\n/gm, '').replace('export class GPUQueue', 'class GPUQueue') + '\nreturn GPUQueue;')(native_);
  const calls = [];
  const queue = GPUQueue.fromNative({ writeTexture: (...args) => calls.push(args) });
  const data = new Uint8Array([9, 1, 2, 3, 8]);
  const texture = { [native_]: 'texture' };
  const layout = { offset: 1, bytesPerRow: 4 };
  for (const input of [data.buffer, data.subarray(1, 4), new DataView(data.buffer, 2, 2)]) queue.writeTexture({ texture }, input, layout, [1, 1]);
  assert.deepEqual(calls.map(call => [...call[1]]), [[9, 1, 2, 3, 8], [1, 2, 3], [2, 3]]);
  assert.ok(calls.every(call => call[1] instanceof Uint8Array && call[1].buffer === data.buffer));
  assert.ok(calls.every(call => call[2] === layout && call[0].texture === 'texture'));
});
