const path = require('node:path');

/** Build-time helper; never imports a runtime SDK or edits application files.
 * Call from nativescript.config.ts; write androidGradle to an app-owned include file.
 * Merge the returned plist/manifest fields into the application's resource templates. */
function monetizationBuild({ purchases = false, rewards, development = false } = {}) {
  if (typeof purchases !== 'boolean' || typeof development !== 'boolean') throw Error('Invalid build flags');
  const ios = { NativeSource: [], SPMPackages: [] };
  const dependencies = [], sources = [];
  const iosInfoPlist = {}, androidManifestMetadata = {};
  const nativeRoot = path.resolve(__dirname, '..');
  // NativeScript joins NativeSource paths to the application directory in its
  // Xcode project. Absolute paths become invalid duplicated paths there.
  function source(feature) {
    ios.NativeSource.push({ name: `Haiyue${feature === 'purchases' ? 'Purchases' : 'Rewards'}`, path: path.relative(process.cwd(), path.join(nativeRoot, feature, 'native/ios/*.swift')).split(path.sep).join('/') });
    sources.push(path.join(nativeRoot, feature, 'native/android'));
  }
  if (purchases) { source('purchases'); dependencies.push('com.android.billingclient:billing:8.3.0'); }
  if (rewards) {
    for (const field of ['iosAppId', 'androidAppId']) {
      if (!/^ca-app-pub-\d{16}~\d{10}$/.test(rewards[field] ?? '')) throw Error(`Invalid ${field}`);
      if (!development && rewards[field].includes('3940256099942544')) throw Error('Demo AdMob App ID in release configuration');
    }
    source('rewards');
    ios.SPMPackages.push({ name: 'GoogleMobileAds', libs: ['GoogleMobileAds'], repositoryURL: 'https://github.com/googleads/swift-package-manager-google-mobile-ads.git', version: '13.10.0' });
    dependencies.push('com.google.android.gms:play-services-ads:25.5.0', 'com.google.android.ump:user-messaging-platform:4.0.0');
    iosInfoPlist.GADApplicationIdentifier = rewards.iosAppId;
    // Defer automatic measurement until the host has completed UMP/ATT.
    iosInfoPlist.GADDelayAppMeasurementInit = true;
    // Xcode expands this build setting. The app never decides debug status from a UI toggle.
    iosInfoPlist.HYBuildConfiguration = '$(CONFIGURATION)';
    androidManifestMetadata['com.google.android.gms.ads.APPLICATION_ID'] = rewards.androidAppId;
  }
  const quote = s => "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
  const androidGradle = `// Generated by @haiyue/native/monetization/build. Regenerate after dependency/path changes.\nandroid {\n${sources.map(s => `    sourceSets.main.java.srcDirs += ${quote(s)}`).join('\n')}\n}\ndependencies {\n${dependencies.map(d => `    implementation ${quote(d)}`).join('\n')}\n}\n`;
  return { ios, androidGradle, iosInfoPlist, androidManifestMetadata };
}
module.exports = { monetizationBuild };
